
package equiscero;
//Autor: Roberto Carlos Castro

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class frmEquiscero extends javax.swing.JFrame {
    //Turno es para determinar si es el turno de "X" o "O"
    //clic es para saber cuandtos clics lleva en cada boton
    int turno=1, clic=1, fila, columna;
    //Matriz para almacenar "X" o "O" y luego ver quien gano
    String Juego[][] = new String [3][3];
    //Vector para almacenar los numero de clics de cada boton
    int NumeroDeClics [] = new int [9];
    String Equis="X", Cero="O", Cambio="", EquisOcero;
    //Asignar las imagenes de "X" y "O" a las variables ImgCero e ImgEquis
    ImageIcon ImgCero = new ImageIcon(getClass().getResource("/Imagenes/Cero.png"));
    ImageIcon ImgEquis = new ImageIcon(getClass().getResource("/Imagenes/Equis.png"));
    /**
     * Creates new form frmEquiscero
     */
    public frmEquiscero() {
        initComponents();
        lbAvisos.setText("Es el turno de X");
        //Inicializa la matriz a guiones
        for (fila = 0; fila < 3; fila++) {
            for (columna = 0; columna < 3; columna++) {
                Juego [fila][columna]="-";
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBoton00 = new javax.swing.JButton();
        btnBoton01 = new javax.swing.JButton();
        btnBoton02 = new javax.swing.JButton();
        btnBoton10 = new javax.swing.JButton();
        btnBoton11 = new javax.swing.JButton();
        btnBoton12 = new javax.swing.JButton();
        btnBoton20 = new javax.swing.JButton();
        btnBoton22 = new javax.swing.JButton();
        lbAvisos = new javax.swing.JLabel();
        btnBoton21 = new javax.swing.JButton();
        lbIcono = new javax.swing.JLabel();
        btnReiniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBoton00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoton00ActionPerformed(evt);
            }
        });

        btnBoton01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoton01ActionPerformed(evt);
            }
        });

        btnBoton02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoton02ActionPerformed(evt);
            }
        });

        btnBoton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoton10ActionPerformed(evt);
            }
        });

        btnBoton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoton11ActionPerformed(evt);
            }
        });

        btnBoton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoton12ActionPerformed(evt);
            }
        });

        btnBoton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoton20ActionPerformed(evt);
            }
        });

        btnBoton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoton22ActionPerformed(evt);
            }
        });

        lbAvisos.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbAvisos.setForeground(new java.awt.Color(0, 153, 204));

        btnBoton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoton21ActionPerformed(evt);
            }
        });

        lbIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoAnimado.gif"))); // NOI18N

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBoton10, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(btnBoton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBoton00, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnBoton01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBoton21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                    .addComponent(btnBoton11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnBoton12, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                    .addComponent(btnBoton22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBoton02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(lbAvisos, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReiniciar)
                        .addGap(90, 90, 90))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(btnReiniciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbAvisos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBoton01, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBoton00, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBoton02, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBoton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBoton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBoton12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBoton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBoton22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBoton21, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Metodo determinar Gandador
    public boolean determinarGanador(){
        boolean Ganador= false;
        //En la primera Intercion del bucle la variabe EquisOcero tiene "X"
        EquisOcero=Equis;
        for (int Cual = 0; Cual < 2; Cual++) {
            if (Juego[0][0].equals(EquisOcero)&&Juego[0][1].equals(EquisOcero)&&Juego[0][2].equals(EquisOcero)) {
                Ganador=true;
                break;
            }
            if (Juego[1][0].equals(EquisOcero)&&Juego[1][1].equals(EquisOcero)&&Juego[1][2].equals(EquisOcero)) {
                Ganador=true;
                break;
            }
            if (Juego[2][0].equals(EquisOcero)&&Juego[2][1].equals(EquisOcero)&&Juego[2][2].equals(EquisOcero)) {
                Ganador=true;
                break;
            }
            if (Juego[0][0].equals(EquisOcero)&&Juego[1][0].equals(EquisOcero)&&Juego[2][0].equals(EquisOcero)) {
                Ganador=true;
                break;
            }
            if (Juego[0][1].equals(EquisOcero)&&Juego[1][1].equals(EquisOcero)&&Juego[2][1].equals(EquisOcero)) {
                Ganador=true;
                break;
            }
            if (Juego[0][2].equals(EquisOcero)&&Juego[1][2].equals(EquisOcero)&&Juego[2][2].equals(EquisOcero)) {
                Ganador=true;
                break;
            }
            if (Juego[0][0].equals(EquisOcero)&&Juego[1][1].equals(EquisOcero)&&Juego[2][2].equals(EquisOcero)) {
                Ganador=true;
                break;
            }
            if (Juego[2][0].equals(EquisOcero)&&Juego[1][1].equals(EquisOcero)&&Juego[0][2].equals(EquisOcero)) {
                Ganador=true;
                break;
            }
            //En la segunda Intercion del bucle la variabe EquisOcero tiene "O"
            EquisOcero=Cero;
        }
        //Devuelve la variable ganador
        return Ganador;
}
    //Metodo reiniciar
    public void reiniciar(){
        //regresa el turno a 1
        turno=1;
        //Muestra el aviso correcto
        lbAvisos.setText("Es el turno de X");
        //Reinicia cero los contadores de los clics
        for (int posicion = 0; posicion < 9; posicion++) {
            NumeroDeClics [posicion] = 0;
        }
        //Reiniciar la matris con guiones
        for (fila = 0; fila < 3; fila++) {
            for (columna = 0; columna < 3; columna++) {
                Juego [fila][columna]="-";
            }
        }
        //Les quita los iconos de Equis o Cero a los botones 
        btnBoton00.setIcon(null);btnBoton01.setIcon(null);btnBoton02.setIcon(null);
        btnBoton10.setIcon(null);btnBoton11.setIcon(null);btnBoton12.setIcon(null);
        btnBoton20.setIcon(null);btnBoton21.setIcon(null);btnBoton22.setIcon(null);
    }

    private void btnBoton00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoton00ActionPerformed
        //Asigna el contador de la posicion 0 a la variable clic
        clic = NumeroDeClics [0];
        //Si la variable clic es mayor a uno se salta la condicion y asi es como se evita que cambie el contenido del boton
        //cuando se le de más de un clic (Para que haga la asignacion del icono solo una vez y no usar setEnabled )
        if (clic<1) {
            //Determina si es el turno de "X" o "O"
            if (turno%2==0) {
                //Si es el turno de cero muestra el icono ImgCero
                btnBoton00.setIcon(ImgCero);
                //Guardar Cero en la matriz
                Juego[0][0]=Cero;
                lbAvisos.setText("Es el turno de X");
            }else{
                //Si es el turno de cero muestra el icono ImgEquis
                btnBoton00.setIcon(ImgEquis);
                //Guardar Equis en la matriz
                Juego[0][0]=Equis;
                lbAvisos.setText("Es el turno de O");
            }
            //Aumentar y guardar los contadores
            turno=turno+1;
            clic=clic+1;
            NumeroDeClics [0] = clic;
        }
        //Ver si ya hay un ganador pasadas 5 jugadas
        if (turno>=5) {
            //Uso del metodo determinarGanador()
            if (determinarGanador()==true) {
                JOptionPane.showMessageDialog(null, "Ya gano "+EquisOcero);
                //Si ya hay ganador usa el metodo reiniciar
                reiniciar();
            }
        }
        //Cuando el turno es 11 y no hay gandor, reinicia el juego
        if (turno==10&&determinarGanador()==false) {
            JOptionPane.showMessageDialog(null, "No hay ganador");
            reiniciar();
        }
    }//GEN-LAST:event_btnBoton00ActionPerformed
//El funcionamiendo de los demas botones es igual
    private void btnBoton01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoton01ActionPerformed
        clic = NumeroDeClics [1];
        if (clic<1) {
            if (turno%2==0) {
                btnBoton01.setIcon(ImgCero);
                Juego[0][1]=Cero;
                lbAvisos.setText("Es el turno de X");
            }
            else{
                btnBoton01.setIcon(ImgEquis);
                Juego[0][1]=Equis;
                lbAvisos.setText("Es el turno de O");
            }
            turno=turno+1;
            clic=clic+1;
            NumeroDeClics [1] = clic;
        }
        if (turno>=5) {
            if (determinarGanador()==true) {
                JOptionPane.showMessageDialog(null, "Ya gano "+EquisOcero);
                reiniciar();
            }
        }
        if (turno==10&&determinarGanador()==false) {
            JOptionPane.showMessageDialog(null, "No hay ganador");
            reiniciar();
        }
    }//GEN-LAST:event_btnBoton01ActionPerformed

    private void btnBoton02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoton02ActionPerformed
        clic = NumeroDeClics [2];
        if (clic<1) {
            if (turno%2==0) {
                btnBoton02.setIcon(ImgCero);
                Juego[0][2]=Cero;
                lbAvisos.setText("Es el turno de X");
            }
            else{
                btnBoton02.setIcon(ImgEquis);
                Juego[0][2]=Equis;
                lbAvisos.setText("Es el turno de O");
            }
            turno=turno+1;
            clic=clic+1;
            NumeroDeClics [2] = clic;
        }
        if (turno>=5) {
            if (determinarGanador()==true) {
                JOptionPane.showMessageDialog(null, "Ya gano "+EquisOcero);
                reiniciar();
            }
        }
        if (turno==10&&determinarGanador()==false) {
            JOptionPane.showMessageDialog(null, "No hay ganador");
            reiniciar();
        }
    }//GEN-LAST:event_btnBoton02ActionPerformed

    private void btnBoton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoton10ActionPerformed
        clic = NumeroDeClics [3];
        if (clic<1) {
            if (turno%2==0) {
                btnBoton10.setIcon(ImgCero);
                Juego[1][0]=Cero;
                lbAvisos.setText("Es el turno de X");
            }
            else{
                btnBoton10.setIcon(ImgEquis);
                Juego[1][0]=Equis;
                lbAvisos.setText("Es el turno de O");
            }
            turno=turno+1;
            clic=clic+1;
            NumeroDeClics [3] = clic;
        }    
        if (turno>=5) {
            if (determinarGanador()==true) {
                JOptionPane.showMessageDialog(null, "Ya gano "+EquisOcero);
                reiniciar();
            }
        }
        if (turno==10&&determinarGanador()==false) {
            JOptionPane.showMessageDialog(null, "No hay ganador");
            reiniciar();
        }
    }//GEN-LAST:event_btnBoton10ActionPerformed

    private void btnBoton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoton11ActionPerformed
        clic = NumeroDeClics [4];
        if (clic<1) {
            if (turno%2==0) {
                btnBoton11.setIcon(ImgCero);
                Juego[1][1]=Cero;
                lbAvisos.setText("Es el turno de X");
            }
            else{
                btnBoton11.setIcon(ImgEquis);
                Juego[1][1]=Equis;
                lbAvisos.setText("Es el turno de O");
            }
            turno=turno+1;
            clic=clic+1;
            NumeroDeClics [4] = clic;
        }    
        if (turno>=5) {
            if (determinarGanador()==true) {
                JOptionPane.showMessageDialog(null, "Ya gano "+EquisOcero);
                reiniciar();
            }
        }
        if (turno==10&&determinarGanador()==false) {
            JOptionPane.showMessageDialog(null, "No hay ganador");
            reiniciar();
        }
    }//GEN-LAST:event_btnBoton11ActionPerformed

    private void btnBoton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoton12ActionPerformed
        clic = NumeroDeClics [5];
        if (clic<1) {
            if (turno%2==0) {
                btnBoton12.setIcon(ImgCero);
                Juego[1][2]=Cero;
                lbAvisos.setText("Es el turno de X");
            }
            else{
                btnBoton12.setIcon(ImgEquis);
                Juego[1][2]=Equis;
                lbAvisos.setText("Es el turno de O");
            }
            turno=turno+1;
            clic=clic+1;
            NumeroDeClics [5] = clic;
        }    
        if (turno>=5) {
            if (determinarGanador()==true) {
                JOptionPane.showMessageDialog(null, "Ya gano "+EquisOcero);
                reiniciar();
            }
        }
        if (turno==10&&determinarGanador()==false) {
            JOptionPane.showMessageDialog(null, "No hay ganador");
            reiniciar();
        }
    }//GEN-LAST:event_btnBoton12ActionPerformed

    private void btnBoton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoton20ActionPerformed
        clic = NumeroDeClics [6];
        if (clic<1) {
            if (turno%2==0) {
                btnBoton20.setIcon(ImgCero);
                Juego[2][0]=Cero;
                lbAvisos.setText("Es el turno de X");
            }
            else{
                btnBoton20.setIcon(ImgEquis);
                Juego[2][0]=Equis;
                lbAvisos.setText("Es el turno de O");
            }
            turno=turno+1;
            clic=clic+1;
            NumeroDeClics [6] = clic;
        }    
        if (turno>=5) {
            if (determinarGanador()==true) {
                JOptionPane.showMessageDialog(null, "Ya gano "+EquisOcero);
                reiniciar();
            }
        }
        if (turno==10&&determinarGanador()==false) {
            JOptionPane.showMessageDialog(null, "No hay ganador");
            reiniciar();
        }
    }//GEN-LAST:event_btnBoton20ActionPerformed

    private void btnBoton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoton21ActionPerformed
        clic = NumeroDeClics [7];
        if (clic<1) {
            if (turno%2==0) {
                btnBoton21.setIcon(ImgCero);
                Juego[2][1]=Cero;
                lbAvisos.setText("Es el turno de X");
            }
            else{
                btnBoton21.setIcon(ImgEquis);
                Juego[2][1]=Equis;
                lbAvisos.setText("Es el turno de O");
            }
            turno=turno+1;
            clic=clic+1;
            NumeroDeClics [7] = clic;
        }    
        if (turno>=5) {
            if (determinarGanador()==true) {
                JOptionPane.showMessageDialog(null, "Ya gano "+EquisOcero);
                reiniciar();
            }
        }
        if (turno==10&&determinarGanador()==false) {
            JOptionPane.showMessageDialog(null, "No hay ganador");
            reiniciar();
        }
    }//GEN-LAST:event_btnBoton21ActionPerformed

    private void btnBoton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoton22ActionPerformed
        clic = NumeroDeClics [8];
        if (clic<1) {
            if (turno%2==0) {
                btnBoton22.setIcon(ImgCero);
                Juego[2][2]=Cero;
                lbAvisos.setText("Es el turno de X");
            }
            else{
                btnBoton22.setIcon(ImgEquis);
                Juego[2][2]=Equis;
                lbAvisos.setText("Es el turno de O");
            }
            turno=turno+1;
            clic=clic+1;
            NumeroDeClics [8] = clic;
        }    
        if (turno>=5) {
            if (determinarGanador()==true) {
                JOptionPane.showMessageDialog(null, "Ya gano "+EquisOcero);
                reiniciar();
            }
        }
        if (turno==10&&determinarGanador()==false) {
            JOptionPane.showMessageDialog(null, "No hay ganador");
            reiniciar();
        }
    }//GEN-LAST:event_btnBoton22ActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        reiniciar();
    }//GEN-LAST:event_btnReiniciarActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEquiscero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEquiscero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEquiscero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEquiscero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEquiscero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoton00;
    private javax.swing.JButton btnBoton01;
    private javax.swing.JButton btnBoton02;
    private javax.swing.JButton btnBoton10;
    private javax.swing.JButton btnBoton11;
    private javax.swing.JButton btnBoton12;
    private javax.swing.JButton btnBoton20;
    private javax.swing.JButton btnBoton21;
    private javax.swing.JButton btnBoton22;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbAvisos;
    private javax.swing.JLabel lbIcono;
    // End of variables declaration//GEN-END:variables
}
